apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-manager
  namespace: argocd
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: dockerhubcredentials
        objectType: secret