{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ (index .Values.ingress.hosts 0).host | quote }}
      http:
        paths:
          - path: {{ (index .Values.ingress.hosts 0).host | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "grafana.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ (index .Values.ingress.hosts 0).host | quote }}
      secretName: {{ (index .Values.ingress.tls 0).secretName }}
  {{- end }}
{{- end }}