replicaCount: 1

image:
  repository: jenkins/jenkins
  tag: lts
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  nodePort: null

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: jenkins.example.com
      paths: ["/"]
  tls: []

rbac:
  create: true
serviceAccount:
  create: true
  name: ""