replicaCount: 1

image:
  repository: jenkins/jenkins
  tag: lts
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080
  nodePort: null

ingress:
  enabled: false

rbac:
  create: true

serviceAccount:
  create: true
  name: "jenkins-sa"

autoscaling:
  enabled: false 
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

persistence:
  enabled: true
  existingClaim: "jenkins-pvc"
  storageClass: "standard"
  accessMode: "ReadWriteOnce"
  size: "8Gi"
