replicaCount: 1

image:
  repository: prometheus-community/prometheus
  tag: lts
  pullPolicy: IfNotPresent.

serviceAccount:
  create: true
  name: "prometheus-sa"

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
