replicaCount: 1

image:
  repository: grafana/grafana
  tag: 7.5.5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  nodePort: null

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: grafana.example.com
      paths: ["/"]
  tls: []

serviceAccount:
  create: true
  name: "grafana-sa"

rbac:
  create: true
