replicaCount: 1

image:
  repository: grafana/grafana
  tag: 7.5.5
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000
  nodePort: null

ingress:
  enabled: false

serviceAccount:
  create: true
  name: "grafana-sa"

rbac:
  create: true