{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "jenkins.fullname" . }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "jenkins.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "jenkins.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
